"""initial schema

Revision ID: 0001_initial
Revises: 
Create Date: 2026-09-14 17:44:55.823463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_initial'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('role', sa.Enum('attendee', 'organizer', 'event_admin', 'platform_admin', name='user_role'), nullable=False),
    sa.Column('locale', sa.String(length=8), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_suspended', sa.Boolean(), nullable=False),
    sa.Column('suspended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_users_email_lower', 'users', [sa.literal_column('lower(email)')], unique=True)
    op.create_table('venues',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('address_line1', sa.String(length=300), nullable=False),
    sa.Column('address_line2', sa.String(length=300), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('latitude', sa.String(length=32), nullable=True),
    sa.Column('longitude', sa.String(length=32), nullable=True),
    sa.Column('has_seat_map', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organizer_profiles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('contact_email', sa.String(length=320), nullable=False),
    sa.Column('contact_phone', sa.String(length=32), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('is_suspended', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_organizer_profile_user')
    )
    op.create_table('venue_sections',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('price_category', sa.String(length=60), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('venue_id', 'name', name='uq_venue_section_name')
    )
    op.create_table('events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organizer_profile_id', sa.UUID(), nullable=False),
    sa.Column('venue_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('slug', sa.String(length=320), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('cover_image_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('draft', 'published', 'unpublished', 'cancelled', 'completed', name='event_status'), nullable=False),
    sa.Column('visibility', sa.Enum('public', 'unlisted', 'private', name='event_visibility'), nullable=False),
    sa.Column('seating_mode', sa.Enum('general_admission', 'assigned_seating', name='seating_mode'), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('registration_opens_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('registration_closes_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('refund_policy', sa.Text(), nullable=True),
    sa.Column('is_suspended', sa.Boolean(), nullable=False),
    sa.Column('duplicated_from_event_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ends_at >= starts_at', name='ck_events_end_after_start'),
    sa.ForeignKeyConstraint(['duplicated_from_event_id'], ['events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organizer_profile_id'], ['organizer_profiles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_events_slug')
    )
    op.create_index('ix_events_organizer_status', 'events', ['organizer_profile_id', 'status'], unique=False)
    op.create_index('ix_events_public_listing', 'events', ['starts_at'], unique=False, postgresql_where=sa.text("status = 'published' AND visibility = 'public'"))
    op.create_table('payout_accounts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organizer_profile_id', sa.UUID(), nullable=False),
    sa.Column('account_holder_name', sa.String(length=200), nullable=False),
    sa.Column('bank_name', sa.String(length=200), nullable=False),
    sa.Column('account_last4', sa.String(length=4), nullable=False),
    sa.Column('status', sa.Enum('unverified', 'pending', 'verified', 'rejected', name='payout_account_status'), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_simulated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organizer_profile_id'], ['organizer_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seat_rows',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=20), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['venue_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('section_id', 'label', name='uq_seat_row_label')
    )
    op.create_table('audit_log_entries',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('action_type', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_action_type', 'audit_log_entries', ['action_type'], unique=False)
    op.create_index('ix_audit_entity', 'audit_log_entries', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_audit_event_occurred', 'audit_log_entries', ['event_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_log_entries_occurred_at'), 'audit_log_entries', ['occurred_at'], unique=False)
    op.create_table('promotional_campaigns',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'active', 'disabled', 'expired', 'exhausted', name='campaign_status'), nullable=False),
    sa.Column('discount_type', sa.Enum('percentage', 'fixed_kzt', name='discount_type'), nullable=False),
    sa.Column('discount_percent', sa.Integer(), nullable=True),
    sa.Column('discount_kzt', sa.BigInteger(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('qr_token', sa.String(length=64), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(discount_type = 'percentage' AND discount_percent IS NOT NULL  AND discount_percent BETWEEN 1 AND 100 AND discount_kzt IS NULL) OR (discount_type = 'fixed_kzt' AND discount_kzt IS NOT NULL  AND discount_kzt >= 0 AND discount_percent IS NULL)", name='ck_campaign_discount_shape'),
    sa.CheckConstraint('ends_at IS NULL OR starts_at IS NULL OR ends_at >= starts_at', name='ck_campaign_window'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qr_token', name='uq_campaign_qr_token')
    )
    op.create_index('ix_campaigns_event', 'promotional_campaigns', ['event_id'], unique=False)
    op.create_table('seats',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('row_id', sa.UUID(), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('is_accessible', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('available', 'held', 'sold', 'unavailable', name='seat_status'), nullable=False),
    sa.Column('position_x', sa.Integer(), nullable=True),
    sa.Column('position_y', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['row_id'], ['seat_rows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('row_id', 'number', name='uq_seat_number_in_row')
    )
    op.create_index('ix_seats_row', 'seats', ['row_id'], unique=False)
    op.create_table('staff_assignments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('event_admin', 'check_in_staff', name='staff_role'), nullable=False),
    sa.Column('assigned_by_user_id', sa.UUID(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_staff_assignment_active', 'staff_assignments', ['event_id', 'user_id'], unique=True, postgresql_where=sa.text('revoked_at IS NULL'))
    op.create_table('ticket_types',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_kzt', sa.BigInteger(), nullable=False),
    sa.Column('quantity_total', sa.Integer(), nullable=False),
    sa.Column('quantity_sold', sa.Integer(), nullable=False),
    sa.Column('quantity_reserved', sa.Integer(), nullable=False),
    sa.Column('max_per_order', sa.Integer(), nullable=False),
    sa.Column('sales_start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sales_end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('max_per_order > 0', name='ck_ticket_types_max_per_order_positive'),
    sa.CheckConstraint('price_kzt >= 0', name='ck_ticket_types_price_non_negative'),
    sa.CheckConstraint('quantity_sold >= 0 AND quantity_reserved >= 0 AND quantity_sold + quantity_reserved <= quantity_total', name='ck_ticket_types_inventory_within_total'),
    sa.CheckConstraint('quantity_total >= 0', name='ck_ticket_types_quantity_non_negative'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ticket_types_event', 'ticket_types', ['event_id'], unique=False)
    op.create_table('promo_codes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('max_redemptions', sa.Integer(), nullable=True),
    sa.Column('redeemed_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('max_redemptions IS NULL OR max_redemptions > 0', name='ck_promo_codes_max_redemptions_positive'),
    sa.CheckConstraint('redeemed_count >= 0 AND (max_redemptions IS NULL OR redeemed_count <= max_redemptions)', name='ck_promo_codes_within_limit'),
    sa.ForeignKeyConstraint(['campaign_id'], ['promotional_campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_promo_codes_campaign', 'promo_codes', ['campaign_id'], unique=False)
    op.create_index('uq_promo_codes_code_lower', 'promo_codes', [sa.literal_column('lower(code)')], unique=True)
    op.create_table('orders',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('reference', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'awaiting_payment', 'confirmed', 'cancelled', 'refunded', 'failed', 'expired', name='order_status'), nullable=False),
    sa.Column('subtotal_kzt', sa.BigInteger(), nullable=False),
    sa.Column('discount_kzt', sa.BigInteger(), nullable=False),
    sa.Column('processing_fee_kzt', sa.BigInteger(), nullable=False),
    sa.Column('total_kzt', sa.BigInteger(), nullable=False),
    sa.Column('refunded_kzt', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('promo_code_id', sa.UUID(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('discount_kzt <= subtotal_kzt', name='ck_orders_discount_within_subtotal'),
    sa.CheckConstraint('refunded_kzt <= total_kzt', name='ck_orders_refund_within_total'),
    sa.CheckConstraint('subtotal_kzt >= 0 AND discount_kzt >= 0 AND processing_fee_kzt >= 0 AND total_kzt >= 0 AND refunded_kzt >= 0', name='ck_orders_money_non_negative'),
    sa.ForeignKeyConstraint(['campaign_id'], ['promotional_campaigns.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['promo_code_id'], ['promo_codes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference', name='uq_orders_reference')
    )
    op.create_index('ix_orders_event_confirmed_at', 'orders', ['event_id', 'confirmed_at'], unique=False, postgresql_where=sa.text("status = 'confirmed'"))
    op.create_index('ix_orders_event_status', 'orders', ['event_id', 'status'], unique=False)
    op.create_index('ix_orders_user_created', 'orders', ['user_id', 'created_at'], unique=False)
    op.create_table('promo_code_ticket_types',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('promo_code_id', sa.UUID(), nullable=False),
    sa.Column('ticket_type_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['promo_code_id'], ['promo_codes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_type_id'], ['ticket_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('promo_code_id', 'ticket_type_id', name='uq_promo_code_ticket_type')
    )
    op.create_table('attendees',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_attendees_order', 'attendees', ['order_id'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('ticket_type_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price_kzt', sa.BigInteger(), nullable=False),
    sa.Column('discount_kzt', sa.BigInteger(), nullable=False),
    sa.Column('line_total_kzt', sa.BigInteger(), nullable=False),
    sa.Column('seat_id', sa.UUID(), nullable=True),
    sa.Column('seat_section', sa.String(length=120), nullable=True),
    sa.Column('seat_row', sa.String(length=20), nullable=True),
    sa.Column('seat_number', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_order_items_quantity_positive'),
    sa.CheckConstraint('unit_price_kzt >= 0 AND discount_kzt >= 0 AND line_total_kzt >= 0', name='ck_order_items_money_non_negative'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seat_id'], ['seats.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_type_id'], ['ticket_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_order_items_order', 'order_items', ['order_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('purpose', sa.Enum('activation_fee', 'ticket_order', name='payment_purpose'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'succeeded', 'failed', 'refunded', name='payment_status'), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount_kzt', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('provider', sa.String(length=60), nullable=False),
    sa.Column('provider_reference', sa.String(length=200), nullable=True),
    sa.Column('card_brand', sa.String(length=40), nullable=True),
    sa.Column('card_last4', sa.String(length=4), nullable=True),
    sa.Column('is_simulated', sa.Boolean(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=120), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('succeeded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount_kzt >= 0', name='ck_payments_amount_non_negative'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_payments_idempotency_key')
    )
    op.create_index('ix_payments_event', 'payments', ['event_id'], unique=False)
    op.create_index('ix_payments_order', 'payments', ['order_id'], unique=False)
    op.create_table('promo_redemptions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('promo_code_id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('discount_kzt', sa.BigInteger(), nullable=False),
    sa.Column('order_total_kzt', sa.BigInteger(), nullable=False),
    sa.Column('redeemed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('discount_kzt >= 0 AND order_total_kzt >= 0', name='ck_promo_redemptions_money_non_negative'),
    sa.ForeignKeyConstraint(['campaign_id'], ['promotional_campaigns.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['promo_code_id'], ['promo_codes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('promo_code_id', 'order_id', name='uq_promo_redemption_code_order')
    )
    op.create_index('ix_promo_redemptions_campaign', 'promo_redemptions', ['campaign_id'], unique=False)
    op.create_table('seat_holds',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('seat_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('ticket_type_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('active', 'released', 'converted', 'expired', name='seat_hold_status'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('quoted_price_kzt', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quoted_price_kzt IS NULL OR quoted_price_kzt >= 0', name='ck_seat_holds_price_non_negative'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['seat_id'], ['seats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_type_id'], ['ticket_types.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_seat_holds_event', 'seat_holds', ['event_id'], unique=False)
    op.create_index('ix_seat_holds_expiry', 'seat_holds', ['expires_at'], unique=False, postgresql_where=sa.text("status = 'active'"))
    op.create_index('uq_seat_hold_active', 'seat_holds', ['seat_id'], unique=True, postgresql_where=sa.text("status = 'active'"))
    op.create_table('paid_sales_activations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('not_started', 'in_progress', 'pending_review', 'active', 'suspended', name='activation_status'), nullable=False),
    sa.Column('has_paid_ticket_type', sa.Boolean(), nullable=False),
    sa.Column('identity_verified', sa.Boolean(), nullable=False),
    sa.Column('payout_account_connected', sa.Boolean(), nullable=False),
    sa.Column('activation_fee_paid', sa.Boolean(), nullable=False),
    sa.Column('terms_accepted', sa.Boolean(), nullable=False),
    sa.Column('activation_fee_kzt', sa.BigInteger(), nullable=False),
    sa.Column('activation_payment_id', sa.UUID(), nullable=True),
    sa.Column('payout_account_id', sa.UUID(), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('suspended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('suspended_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('activation_fee_kzt >= 0', name='ck_activation_fee_non_negative'),
    sa.ForeignKeyConstraint(['activation_payment_id'], ['payments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payout_account_id'], ['payout_accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', name='uq_activation_event')
    )
    op.create_table('refunds',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'succeeded', 'failed', name='refund_status'), nullable=False),
    sa.Column('amount_kzt', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('initiated_by_user_id', sa.UUID(), nullable=False),
    sa.Column('is_simulated', sa.Boolean(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=120), nullable=False),
    sa.Column('provider_reference', sa.String(length=200), nullable=True),
    sa.Column('succeeded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount_kzt >= 0', name='ck_refunds_amount_non_negative'),
    sa.ForeignKeyConstraint(['initiated_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_refunds_idempotency_key')
    )
    op.create_index('ix_refunds_order', 'refunds', ['order_id'], unique=False)
    op.create_table('tickets',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ticket_number', sa.String(length=40), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('order_item_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('ticket_type_id', sa.UUID(), nullable=False),
    sa.Column('attendee_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('valid', 'checked_in', 'cancelled', 'refunded', name='ticket_status'), nullable=False),
    sa.Column('admission_token', sa.String(length=64), nullable=False),
    sa.Column('seat_id', sa.UUID(), nullable=True),
    sa.Column('seat_section', sa.String(length=120), nullable=True),
    sa.Column('seat_row', sa.String(length=20), nullable=True),
    sa.Column('seat_number', sa.String(length=20), nullable=True),
    sa.Column('price_kzt', sa.BigInteger(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('price_kzt >= 0', name='ck_tickets_price_non_negative'),
    sa.ForeignKeyConstraint(['attendee_id'], ['attendees.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['seat_id'], ['seats.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_type_id'], ['ticket_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admission_token', name='uq_tickets_admission_token'),
    sa.UniqueConstraint('ticket_number', name='uq_tickets_number')
    )
    op.create_index('ix_tickets_event_status', 'tickets', ['event_id', 'status'], unique=False)
    op.create_index('ix_tickets_order', 'tickets', ['order_id'], unique=False)
    op.create_index('uq_ticket_active_seat', 'tickets', ['event_id', 'seat_id'], unique=True, postgresql_where=sa.text("seat_id IS NOT NULL AND status NOT IN ('cancelled', 'refunded')"))
    op.create_table('check_in_records',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('checked_in_by_user_id', sa.UUID(), nullable=False),
    sa.Column('method', sa.Enum('qr_scan', 'manual_search', name='check_in_method'), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reversed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reversed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('reversal_reason', sa.Text(), nullable=True),
    sa.Column('device_label', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['checked_in_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reversed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_check_in_records_event', 'check_in_records', ['event_id', 'checked_in_at'], unique=False)
    op.create_index('uq_checkin_active_ticket', 'check_in_records', ['ticket_id'], unique=True, postgresql_where=sa.text('reversed_at IS NULL'))
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('account_verification', 'registration_confirmation', 'payment_failure', 'ticket_delivery', 'event_update', 'event_cancellation', 'refund_completed', 'payout_status', 'support_new_message', 'support_case_assigned', 'support_status_change', name='notification_type'), nullable=False),
    sa.Column('channel', sa.Enum('email', 'in_app', name='notification_channel'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'sent', 'failed', 'read', name='notification_status'), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('ticket_id', sa.UUID(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_user_created', 'notifications', ['user_id', 'created_at'], unique=False)
    op.create_table('support_cases',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('reference', sa.String(length=32), nullable=False),
    sa.Column('opened_by_user_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('ticket_delivery', 'payment', 'refund', 'seating', 'event_information', 'check_in', 'account', 'technical', name='support_category'), nullable=False),
    sa.Column('status', sa.Enum('open', 'in_progress', 'waiting_for_customer', 'resolved', name='support_case_status'), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=False),
    sa.Column('is_organizer_case', sa.Boolean(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('ticket_id', sa.UUID(), nullable=True),
    sa.Column('assigned_to_user_id', sa.UUID(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['opened_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference', name='uq_support_cases_reference')
    )
    op.create_index('ix_support_cases_assigned', 'support_cases', ['assigned_to_user_id', 'status'], unique=False)
    op.create_index('ix_support_cases_event_status', 'support_cases', ['event_id', 'status'], unique=False)
    op.create_index('ix_support_cases_opened_by', 'support_cases', ['opened_by_user_id', 'created_at'], unique=False)
    op.create_table('support_messages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('author_user_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_internal_note', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['case_id'], ['support_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_support_messages_case_created', 'support_messages', ['case_id', 'created_at'], unique=False)
    # ### end Alembic commands ###



    # ------------------------------------------------------------------
    # SRS 4.16: "Audit entries shall not be editable or deletable through normal
    # organizer interfaces."
    #
    # A trigger rather than `REVOKE UPDATE, DELETE`, because a grant applies to one role
    # and the team connects as the table owner in development -- which is exactly where
    # an accidental UPDATE gets written. A trigger holds for every role, owner included,
    # and survives `docker compose down -v`.
    #
    # Deliberately has no escape hatch: a genuine correction is a new compensating entry,
    # not an edit to history.
    # ------------------------------------------------------------------
    op.execute(
        """
        CREATE OR REPLACE FUNCTION biletflow_audit_append_only()
        RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION
                'audit_log_entries is append-only (SRS 4.16): % is not permitted',
                TG_OP
                USING ERRCODE = 'restrict_violation';
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER audit_log_no_update_delete
        BEFORE UPDATE OR DELETE ON audit_log_entries
        FOR EACH ROW EXECUTE FUNCTION biletflow_audit_append_only();
        """
    )
    # ### end BiletFlow hand-written section ###


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TRIGGER IF EXISTS audit_log_no_update_delete ON audit_log_entries")
    op.execute("DROP FUNCTION IF EXISTS biletflow_audit_append_only()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_support_messages_case_created', table_name='support_messages')
    op.drop_table('support_messages')
    op.drop_index('ix_support_cases_opened_by', table_name='support_cases')
    op.drop_index('ix_support_cases_event_status', table_name='support_cases')
    op.drop_index('ix_support_cases_assigned', table_name='support_cases')
    op.drop_table('support_cases')
    op.drop_index('ix_notifications_user_created', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('uq_checkin_active_ticket', table_name='check_in_records', postgresql_where=sa.text('reversed_at IS NULL'))
    op.drop_index('ix_check_in_records_event', table_name='check_in_records')
    op.drop_table('check_in_records')
    op.drop_index('uq_ticket_active_seat', table_name='tickets', postgresql_where=sa.text("seat_id IS NOT NULL AND status NOT IN ('cancelled', 'refunded')"))
    op.drop_index('ix_tickets_order', table_name='tickets')
    op.drop_index('ix_tickets_event_status', table_name='tickets')
    op.drop_table('tickets')
    op.drop_index('ix_refunds_order', table_name='refunds')
    op.drop_table('refunds')
    op.drop_table('paid_sales_activations')
    op.drop_index('uq_seat_hold_active', table_name='seat_holds', postgresql_where=sa.text("status = 'active'"))
    op.drop_index('ix_seat_holds_expiry', table_name='seat_holds', postgresql_where=sa.text("status = 'active'"))
    op.drop_index('ix_seat_holds_event', table_name='seat_holds')
    op.drop_table('seat_holds')
    op.drop_index('ix_promo_redemptions_campaign', table_name='promo_redemptions')
    op.drop_table('promo_redemptions')
    op.drop_index('ix_payments_order', table_name='payments')
    op.drop_index('ix_payments_event', table_name='payments')
    op.drop_table('payments')
    op.drop_index('ix_order_items_order', table_name='order_items')
    op.drop_table('order_items')
    op.drop_index('ix_attendees_order', table_name='attendees')
    op.drop_table('attendees')
    op.drop_table('promo_code_ticket_types')
    op.drop_index('ix_orders_user_created', table_name='orders')
    op.drop_index('ix_orders_event_status', table_name='orders')
    op.drop_index('ix_orders_event_confirmed_at', table_name='orders', postgresql_where=sa.text("status = 'confirmed'"))
    op.drop_table('orders')
    op.drop_index('uq_promo_codes_code_lower', table_name='promo_codes')
    op.drop_index('ix_promo_codes_campaign', table_name='promo_codes')
    op.drop_table('promo_codes')
    op.drop_index('ix_ticket_types_event', table_name='ticket_types')
    op.drop_table('ticket_types')
    op.drop_index('uq_staff_assignment_active', table_name='staff_assignments', postgresql_where=sa.text('revoked_at IS NULL'))
    op.drop_table('staff_assignments')
    op.drop_index('ix_seats_row', table_name='seats')
    op.drop_table('seats')
    op.drop_index('ix_campaigns_event', table_name='promotional_campaigns')
    op.drop_table('promotional_campaigns')
    op.drop_index(op.f('ix_audit_log_entries_occurred_at'), table_name='audit_log_entries')
    op.drop_index('ix_audit_event_occurred', table_name='audit_log_entries')
    op.drop_index('ix_audit_entity', table_name='audit_log_entries')
    op.drop_index('ix_audit_action_type', table_name='audit_log_entries')
    op.drop_table('audit_log_entries')
    op.drop_table('seat_rows')
    op.drop_table('payout_accounts')
    op.drop_index('ix_events_public_listing', table_name='events', postgresql_where=sa.text("status = 'published' AND visibility = 'public'"))
    op.drop_index('ix_events_organizer_status', table_name='events')
    op.drop_table('events')
    op.drop_table('venue_sections')
    op.drop_table('organizer_profiles')
    op.drop_table('venues')
    op.drop_index('uq_users_email_lower', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###

    # Drop the native enum types the CREATE TABLEs implicitly created.
    op.execute("DROP TYPE IF EXISTS activation_status")
    op.execute("DROP TYPE IF EXISTS campaign_status")
    op.execute("DROP TYPE IF EXISTS check_in_method")
    op.execute("DROP TYPE IF EXISTS discount_type")
    op.execute("DROP TYPE IF EXISTS event_status")
    op.execute("DROP TYPE IF EXISTS event_visibility")
    op.execute("DROP TYPE IF EXISTS notification_channel")
    op.execute("DROP TYPE IF EXISTS notification_status")
    op.execute("DROP TYPE IF EXISTS notification_type")
    op.execute("DROP TYPE IF EXISTS order_status")
    op.execute("DROP TYPE IF EXISTS payment_purpose")
    op.execute("DROP TYPE IF EXISTS payment_status")
    op.execute("DROP TYPE IF EXISTS payout_account_status")
    op.execute("DROP TYPE IF EXISTS refund_status")
    op.execute("DROP TYPE IF EXISTS seat_hold_status")
    op.execute("DROP TYPE IF EXISTS seat_status")
    op.execute("DROP TYPE IF EXISTS seating_mode")
    op.execute("DROP TYPE IF EXISTS staff_role")
    op.execute("DROP TYPE IF EXISTS support_case_status")
    op.execute("DROP TYPE IF EXISTS support_category")
    op.execute("DROP TYPE IF EXISTS ticket_status")
    op.execute("DROP TYPE IF EXISTS user_role")
